linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

  disable:
    - dupl
    - depguard
    - testpackage
    - varnamelen
    - wsl
    - nlreturn
    - revive

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - dupl
        - lll
        - funlen
