version: "2"

linters:
  default: all
  disable:
    - revive
    - testpackage
    - varnamelen
    - wsl
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - depguard
          - dupl
          - funlen
          - lll
          - maintidx

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
