name: Auto Commit (Go)

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  go-generate:
    uses: typisttech/.github/.github/workflows/create-auto-merged-pull-request-go.yml@v1
    permissions:
      contents: write
      pull-requests: write
    with:
      command: go generate ./...
      branch: "bot/go-generate/${{ github.ref_name }}"
      labels: |
        bot
        go-generate
    secrets:
      pr-write-pat-token: ${{ secrets.PR_WRITE_PAT_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}
