name: Go Proxy
on:
  push:

permissions: {}

jobs:
  go-proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
      - run: go list -m -u -json -x github.com/${{ github.repository }}@${{ github.sha }}
        env:
          GOPROXY: https://proxy.golang.org
          GOSUMDB: sum.golang.org
      - run: go list -m -u -json -x github.com/${{ github.repository }}@${{ github.ref_name }}
        env:
          GOPROXY: https://proxy.golang.org
          GOSUMDB: sum.golang.org
