name: Go

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          only-new-issues: true
          args: --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go mod tidy -diff
      - run: go mod download
      - run: go mod verify
      - run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.out -covermode=atomic ./...
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

  codecov:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v5
        with:
          name: coverage
      - uses: codecov/codecov-action@v5
        with:
          use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
