name: govulncheck

on:
  schedule:
    - cron: '13 05 * * *' # Daily at 05:13 UTC
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go version
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: govulncheck --show version -test ./...
